# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='latest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Build'),
        ),
    ]
