# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20160424_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='latest',
        ),
        migrations.AddField(
            model_name='build',
            name='package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.Package'),
        ),
    ]
