# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20160424_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='log_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='build',
            name='result_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('BUILDING', 'Building'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default=('BUILDING', 'Building'), max_length=100),
        ),
    ]
