# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20160521_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='log_path',
        ),
        migrations.RemoveField(
            model_name='build',
            name='result_path',
        ),
    ]
