# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20160530_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='sha256',
            field=models.CharField(default='', max_length=100),
        ),
    ]
