# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_build_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
