# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='sha256',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
