# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20161127_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='server',
            field=models.CharField(default='OFFICIAL', max_length=100),
        ),
    ]
